services:
  - type: web
    name: playtest-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: playtest-db
          property: connectionString
  - type: pserv
    name: playtest-db
    env: postgresql
    plan: free
    databaseName: playtest_db
    databaseUser: playtest_user